### ISSUE TITLE
Automated test of notebook 4 fails - missing kernel error

### ISSUE THREAD

**Issue by tngTUDOR** [brightway-lca/from-the-ground-up#5]
## Current
When running the `pytest` + `nbmake` tests, notebook 4 fails with:

```
FAILED 4 - Interpretation.ipynb:: - Error - No such kernel: 'conda-env-regional-py'
```

## Expected
Github action tests this specific kernel. 

Regular pytest has markers to allow testing specific places. The current github action collects all tests, and runs all tests. We might need to separate the "regionalization" tests to a different run so that we can instantiate the regionalization kernel.

**Comment by tngTUDOR** [comment]
nbmake does have options for other kernels:

[https://github.com/treebeardtech/nbmake#override-notebook-kernels-when-testing](https://github.com/treebeardtech/nbmake#override-notebook-kernels-when-testing)

**Comment by michaelweinold** [comment]
This was fixed with https://github.com/brightway-lca/from-the-ground-up/commit/440a7b5bba95c5cb47df80d756f7a74a9a9a020b. The workflow [has been updated]:

```bash
run: pytest --nbmake --nbmake-kernel=conda_environment_actions_workflow *ipynb
```
